//
//  RecordStatusCode.h
//  RecordDemo
//
//  Created by Xiaoz on 16/4/9.
//  Copyright © 2016年 Luistrue. All rights reserved.
//

#ifndef RecordStatusCode_h
#define RecordStatusCode_h

#define ERROR_ALLOC_AVFORMAT_OUT	-1000
#define ERROR_ALLOC_AVFORMA			-1001
#define ERROR_ALLOC_BUFFER			-1002
#define ERROR_ALLOC_IOCTX			-1003
#define ERROR_NEW_VIDEO_STREAM		-1004
#define ERROR_NEW_AUDIO_STREAM		-1005
#define ERROR_OUTPUT_FILE_PATH		-1006
#define ERROR_OUTPUT_FILE_OPEN		-1007

#define ERROR_INPUT_FILE_PATH_VIDEO		-1010
#define ERROR_INPUT_FILE_OPEN_VIDEO		-1011
#define ERROR_INPUT_FILE_FORMAT_VIDEO	-1012
#define ERROR_INPUT_FILE_FRAME_VIDEO	-1013
#define ERROR_INPUT_FILE_PATH_AUDIO		-1014
#define ERROR_INPUT_FILE_OPEN_AUDIO		-1015
#define ERROR_INPUT_FILE_FORMAT_AUDIO	-1016
#define ERROR_INPUT_FILE_FRAME_AUDIO	-1017

#define ERROR_OUTPUT_FRAME_INIT_VIDEO	-1020
#define ERROR_OUTPUT_BUFF_SIZE_VIDEO	-1021
#define ERROR_OUTPUT_FRAME_INIT_AUDIO	-1022
#define ERROR_OUTPUT_FRAME_FILL_AUDIO	-1023
#define ERROR_OUTPUT_BUFF_SIZE_AUDIO	-1024
#define ERROR_CONVERTING_AUDIO			-1025


#define ERROR_CODE_DE_VIDEO				-1030
#define ERROR_CODE_DE_AUDIO				-1031
#define ERROR_CODE_DE_FIND_VIDEO		-1032
#define ERROR_CODE_DE_OPEN_VIDEO		-1033
#define ERROR_CODE_DE_FIND_AUDIO		-1034
#define ERROR_CODE_DE_OPEN_AUDIO		-1035

#define ERROR_CODE_EN_VIDEO				-1040
#define ERROR_CODE_EN_FIND_VIDEO		-1041
#define ERROR_CODE_EN_OPEN_VIDEO		-1042
#define ERROR_CODE_EN_AUDIO				-1043
#define ERROR_CODE_EN_FIND_AUDIO		-1044
#define ERROR_CODE_EN_INIT_AUDIO		-1045
#define ERROR_CODE_EN_CHCK_AUDIO		-1046
#define ERROR_CODE_EN_OPEN_AUDIO		-1047


#define ERROR_WRITE_VIDEO				-1050
#define ERROR_WRITE_AUDIO				-1051

#endif /* RecordStatusCode_h */
